/*
 * EBI Dbfetch Databases List
 *
 */

exports.dbFetchDBs = [
	{ description:"EDAM", name: "edam" },
	{ description:"EMBL-Bank", name:"embl" },
	{ description:"EMBLCDS", name:"mblcds" },
	{ description:"EMBLCON", name:"emblcon" },
	{ description:"EMBLCONEXP", name:"emblconexp" },
	{ description:"EMBL-SVA", name:"emblsva" },
	{ description:"Ensembl Gene", name:"ensemblgene" },
	{ description:"Ensembl Genomes Gene", name:"ensemblgenomesgene" },
	{ description:"Ensembl Genomes Transcript", name:"ensemblgenomestranscript" },
	{ description:"Ensembl Transcript", name:"ensembltranscript" },
	{ description:"EPO Proteins", name:"epo_prt)" },
	{ description:"HGNC", name:"hgnc" },
	{ description:"IMGT/HLA", name:"imgthla" },
	{ description:"IMGT/LIGM-DB", name:"imgtligm" },
	{ description:"InterPro", name:"interpro" },
	{ description:"IPD-KIR", name:"ipdkir" },
	{ description:"IPD-MHC", name:"ipdmhc" },
	{ description:"IPRMC", name:"iprmc" },
	{ description:"IPRMC UniParc", name:"iprmcuniparc" },
	{ description:"JPO Proteins", name:"jpo_prt" },
	{ description:"KIPO Proteins", name:"kipo_prt" },
	{ description:"MEDLINE", name:"medline" },
	{ description:"Patent DNA NRL1", name:"nrnl1" },
	{ description:"Patent DNA NRL2", name:"nrnl2" },
	{ description:"Patent Protein NRL1", name:"nrpl1" },
	{ description:"Patent Protein NRL2", name:"nrpl2" },
	{ description:"Patent Equivalents", name:"patent_equivalents" },
	{ description:"PDB", name:"pdb" },
	{ description:"RefSeq (nucleotide)", name:"refseqn" },
	{ description:"RefSeq (protein)", name:"refseqp" },
	{ description:"SGT", name:"sgt" },
	{ description:"Taxonomy", name:"taxonomy" },
	{ description:"Trace Archive", name:"tracearchive" },
	{ description:"UniParc", name:"uniparc" },
	{ description:"UniProtKB", name:"uniprotkb" },
	{ description:"UniRef100", name:"uniref100" },
	{ description:"UniRef50", name:"uniref50" },
	{ description:"UniRef90", name:"uniref90" },
	{ description:"UniSave", name:"unisave" },
	{ description:"USPTO Proteins", name:"uspto_prt" }
]